name: mikemcgirr-com
version: '0.2.0'
author: Mike McGirr
maintainer: mike@oatsmail.com
license: GPL-3

dependencies:
  - base == 4.*
  - hakyll == 4.13.*

executables:
  site:
    main: site.hs
    ghc-options:
      - -threaded
      - -Wall
